[mysqld]

bind-address = 0.0.0.0					# permet aux autres containers de se connecter a mariadb. Elle ecoute sur toutes les interfaces reseau

skip-name-resolve						# evite les resolutions DNS, cad que mariadb n'essaie pas de convertir les ip en nom de domaine -> evite pb reseaux dans docker et meilleure performances
										# connexions uniquement pas ip

character-set-server = utf8mb4			# definit encodage. utilisé pour supporter tous les caractères Unicode, notamment pour WordPress

collation-server = utf8mb4_general_ci	# definit les regles de comparaison des chaines.

