[www]

; En INI les commentaires s'ecrivent avec ; sinon crash le programme

; Ce fichier est la config d'un pool de workers php-fpm ->www
; php-fpm est un gestionnaire de processus qui execute du code php, donc wordpress, pour des serveurs comme nginx.
; il recoit des requetes de nginx via fast cgi

; www definit un pool de processus php


; definit l'utilisateur linux des workers php
; www-data est l'utilisateur standard pour les services web
user = www-data
group = www-data

; php-fpm ecoute sur le port 9000, nginx connecte a wordpress:9000, communication via reseau docker
listen = 9000

; permission sur le socket/port -> proprietaire, groupe, lecture et ecriture pour owner et group
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; par defaut php-fpm nettoie toutes les variables d'environnement, ici on veut les garder
clear_env = no

; Process manager
; mode de gestion des processus dynamic -> s'ajuste automatiquement. bon compromis perf/memoire 
pm = dynamic

; nombre max de workers php, sachant que charque worker traite 1 requete a la fois
pm.max_children = 5

; nombre de worker au demarrage
pm.start_servers = 2

; gestion des workers "idle", min -> garde au moins 1 pret, max -> pas plus de 3 inutiles
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; nombre de requete max par worker, apres 500 requetes, le worker est redemarre
pm.max_requests = 500




; Comment ca fonctionne dans le projet:
; client -> nginx -> php-fpm -> wordpress -> reponse html -> nginx -> client

; Nginx ne sait pas exécuter du code PHP, il ne fait que servir des fichiers. PHP-FPM est un service séparé 
; qui exécute le code PHP via le protocole FastCGI. Nginx lui transmet les requêtes PHP, 
; et PHP-FPM renvoie du HTML déjà interprété